spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/course}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}

flyway:
  url: ${DB_URL:jdbc:postgresql://localhost:5432/course}
  user: ${DB_USERNAME:postgres}
  password: ${DB_PASSWORD:123456}
  enabled: true
  locations:
    - 'classpath:db/migration'

logging:
  level:
    org:
      springframework:
        security: TRACE

server:
  error:
    include-message: always
